import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Where the shipped templates live.
 *
 * Resolved relative to this module rather than to the working directory, so the
 * generator works from anywhere and from an installed package.
 */
const TEMPLATES = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "..",
  "templates",
  "constitution",
);

export const PRESETS = ["codebase", "research"] as const;
export type Preset = (typeof PRESETS)[number];

export interface ComposeOptions {
  preset?: Preset;
  /** Where the composed file will live, named in its header for orientation. */
  filename?: string;
}

const GENERATED_HEADER = `<!--
  Generated by \`accreta init\`.

  Composed from templates/constitution/. Edit freely — this file is yours, and
  nothing regenerates it behind your back. The composition is recorded below so
  a later reader can tell what it started as.
-->`;

/**
 * Compose the constitution an agent follows for this knowledge base.
 *
 * `base.md` carries the method and assumes nothing about source type; a preset
 * adds domain vocabulary. Keeping them separate is what stops the method from
 * quietly acquiring code-shaped assumptions, which is the same reason page types
 * live in configuration.
 */
export function composeConstitution(options: ComposeOptions = {}): string {
  const base = readTemplate("base.md");
  const parts = [GENERATED_HEADER, "", base];

  if (options.preset) {
    const preset = readTemplate(join("presets", `${options.preset}.md`));
    parts.push("", "---", "", preset);
  }

  parts.push(
    "",
    "---",
    "",
    `<!-- composed from: base.md${options.preset ? ` + presets/${options.preset}.md` : ""} -->`,
    "",
  );

  return parts.join("\n");
}

function readTemplate(relativePath: string): string {
  const path = join(TEMPLATES, relativePath);
  if (!existsSync(path)) {
    throw new Error(`Constitution template not found: ${relativePath}`);
  }
  return readFileSync(path, "utf-8").trim();
}

/** Does this look like a preset name? */
export function isPreset(value: string): value is Preset {
  return (PRESETS as readonly string[]).includes(value);
}
